### ISSUE TITLE
Setup project with Astro.js

### ISSUE THREAD

**Issue by jenniferhail** [jenniferhail/ihavecovid#1]
Goal: Update the repo from it's current bare-bones setup to [Astro.js](https://astro.build/).

Why: I've been wanting to play with Astro for a while now and this will be a great opportunity to get started. I definitely want this project to use a modern stack, but for a fast setup (two nights working on this landing page after work), I stuck with the basics.

**Comment by millertchris** [comment]
@jenniferhail I would definitely make this a first priority since it will dictate how folders/files are organized and also how the code will be organized.

**Comment by jenniferhail** [comment]
@millertchris I was able to migrate the landing page over to Astro within an hour. :)
